resources:
  - ../../base/api-ticket
  - ingressroute.yaml

configMapGenerator:
  - name: api-ticket-config
    envs:
      - config/env.properties

secretGenerator:
  - name: bigtable-credential
    files:
      - config/google-credential.json
